spring.application.name=DATN - HatHub

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HatHubDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=12

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoananh123bo@gmail.com
spring.mail.password=lgdkijxqnwkxirtv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# t?t session khi rerun ch??ng trình
server.servlet.session.persistent=false